name: Containers

on:
  workflow_call:
    inputs:
      imageTag:
        description: The image tag
        required: true
        type: string
      platforms:
        description: The target platforms to build
        required: true
        type: string
        # we limit this to amd64, in order to reduce build times for releases
        default: "linux/amd64"
  workflow_dispatch:
    inputs:
      imageTag:
        description: The image tag
        required: true
        type: string
        default: latest
      platforms:
        description: The target platforms to build
        required: true
        type: string
        default: "linux/amd64, linux/arm64"

env:
  IMAGE_NAME: seedwing-policy-server
  IMAGE_TAG: ${{ inputs.imageTag }}

jobs:
  build-containers:

    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-22.04
    steps:

      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: "ghcr.io"

      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAG }}
          platforms: ${{ inputs.platforms }}
          containerfiles: |
            ./Dockerfile

      - name: Check images created
        run: buildah images | grep '${{ env.IMAGE_NAME }}'

      - name: Check manifest
        run: |
          set -x
          buildah manifest inspect '${{ steps.build-image.outputs.image }}:${{ env.IMAGE_TAG }}'

      - name: Push to ghcr.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/${{ github.actor }}
